# Generated by Django 4.0.3 on 2022-03-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=1, max_length=64, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default=1, max_length=64, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=1, max_length=64, verbose_name='Ник'),
            preserve_default=False,
        ),
    ]
