# Generated by Django 4.0.3 on 2022-03-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_name_customuser_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='surname',
            new_name='last_name',
        ),
    ]
