# Generated by Django 4.0.3 on 2022-03-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0012_alter_book_visibility'),
        ('user', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='added_books',
            field=models.ManyToManyField(blank=True, related_name='book_from_mine', to='library.book', verbose_name='Добавленные книги'),
        ),
    ]
